# Generated by Django 5.2.9 on 2026-02-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_customsolanapayment_paid_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custompaymenttoken",
            name="payment_crypto_price",
            field=models.DecimalField(
                decimal_places=18,
                help_text="Payment price in cryptocurrency",
                max_digits=30,
            ),
        ),
    ]
