# Generated by Django 5.2.9 on 2026-01-25 14:35

import django.db.models.deletion
from django.db import migrations, models

import django_solana_payments.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_solana_payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomPaymentToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "token_type",
                    models.CharField(
                        choices=[("NATIVE", "Native"), ("SPL", "SPL Token")],
                        db_index=True,
                        max_length=15,
                    ),
                ),
                (
                    "mint_address",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "payment_crypto_price",
                    models.DecimalField(decimal_places=18, max_digits=30),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=10)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomSolanaPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_address", models.CharField(max_length=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("finalized", "Finalized"),
                            ("confirmed", "Confirmed"),
                            ("processed", "Processed"),
                            ("expired", "Expired"),
                        ],
                        max_length=10,
                    ),
                ),
                ("signature", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "expiration_date",
                    models.DateTimeField(
                        default=django_solana_payments.utils.set_default_expiration_date
                    ),
                ),
                ("meta_data", models.JSONField(blank=True, default=dict, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "customer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "crypto_prices",
                    models.ManyToManyField(
                        related_name="%(app_label)s_%(class)s_payments",
                        to="django_solana_payments.solanapaypaymentcryptoprice",
                    ),
                ),
                (
                    "one_time_payment_wallet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_payment",
                        to="django_solana_payments.onetimepaymentwallet",
                    ),
                ),
                (
                    "paid_token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_solana_payments.paymentcryptotoken",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
