# Generated by Django 5.2.9 on 2026-01-25 14:35

import django.db.models.deletion
import django_solana_payments.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OneTimePaymentWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keypair_json", models.JSONField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("received_funds", "Received Funds"),
                            ("sent_funds", "Sent Funds"),
                            ("processing_payment", "Processing Payment"),
                            ("processing_funds", "Processing Funds"),
                            ("failed_to_send_funds", "Failed To Send Funds"),
                            ("payment_expired", "Payment Expired"),
                            (
                                "payment_expired_and_wallet_closed",
                                "Payment Expired And Wallet Closed",
                            ),
                        ],
                        default="created",
                        max_length=50,
                    ),
                ),
                (
                    "receiver_address",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentCryptoToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "token_type",
                    models.CharField(
                        choices=[("NATIVE", "Native"), ("SPL", "SPL Token")],
                        db_index=True,
                        max_length=15,
                    ),
                ),
                (
                    "mint_address",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "payment_crypto_price",
                    models.DecimalField(decimal_places=18, max_digits=30),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("symbol", models.CharField(max_length=128, unique=True)),
                ("meta_data", models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("mint_address__isnull", False), ("token_type", "SPL")
                            ),
                            models.Q(
                                ("mint_address__isnull", True), ("token_type", "NATIVE")
                            ),
                            _connector="OR",
                        ),
                        name="mint_address_consistency",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SolanaPayPaymentCryptoPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_in_crypto",
                    models.DecimalField(decimal_places=18, max_digits=30),
                ),
                ("meta_data", models.JSONField(blank=True, default=dict)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crypto_prices",
                        to="django_solana_payments.paymentcryptotoken",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolanaPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_address", models.CharField(max_length=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("finalized", "Finalized"),
                            ("confirmed", "Confirmed"),
                            ("processed", "Processed"),
                            ("expired", "Expired"),
                        ],
                        max_length=10,
                    ),
                ),
                ("signature", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "expiration_date",
                    models.DateTimeField(
                        default=django_solana_payments.utils.set_default_expiration_date
                    ),
                ),
                ("meta_data", models.JSONField(blank=True, default=dict, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "one_time_payment_wallet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_payment",
                        to="django_solana_payments.onetimepaymentwallet",
                    ),
                ),
                (
                    "paid_token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_solana_payments.paymentcryptotoken",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solana_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "crypto_prices",
                    models.ManyToManyField(
                        related_name="%(app_label)s_%(class)s_payments",
                        to="django_solana_payments.solanapaypaymentcryptoprice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
